name: Docker swarm

on:
  push:
    branches:
      - main  # Trigger workflow on push to the 'main' branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: self-hosted  # Ensure this matches your runner label

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo usermod -aG docker $USER
            newgrp docker
          fi
          # Ensure the Docker socket has correct permissions
          sudo chmod 666 /var/run/docker.sock

      - name: Docker Info
        run: docker info

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kishore1092001/simple-app:latest

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull the latest Docker image
        run: docker pull kishore1092001/simple-app:latest

      - name: Deploy Docker stack to Swarm
        run: |
          # Deploy to the master node
          ssh ubuntu@44.203.250.222 'docker stack deploy --compose-file /path/to/docker-compose.yml app'
          
          # Optionally, you can add commands to pull the latest image explicitly on the worker node
          # and update the stack if needed
          ssh ubuntu@3.86.206.29 'docker stack deploy --compose-file /path/to/docker-compose.yml app'
