name: Build, Push Docker Image, and Deploy

on:
  push:
    branches:
      - main  # Trigger workflow on push to the 'main' branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: self-hosted  # Ensure this matches your runner label

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
            sudo usermod -aG docker $USER
            newgrp docker
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kishore1092001/simple-app:latest

      # Optional: SonarQube Scan
      # - name: SonarQube Scan
      #   run: |
      #     docker run --rm \
      #       -e SONAR_HOST_URL=${{ secrets.SONARQUBE_URL }} \
      #       -e SONAR_TOKEN=${{ secrets.SONARQUBE_TOKEN }} \
      #       -v $(pwd):/usr/src \
      #       sonarsource/sonar-scanner-cli \
      #       -Dsonar.projectKey=action \
      #       -Dsonar.sources=. \
      #       -Dsonar.host.url=${{ secrets.SONARQUBE_URL }} \
      #       -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy to Docker Swarm
        run: |
          # Deploy stack to master node
          ssh ubuntu@44.203.250.222 'docker stack deploy --compose-file docker-compose.yaml app'
          
          # Ensure images are pulled on worker nodes
          ssh ubuntu@44.203.250.222 'docker service update --image kishore1092001/simple-app:latest app_web'
